import Head from 'next/head'
import Image from 'next/image'
import NewArrivage from '../components/NewArrivage/NewArrivage'
import NewsLetter from '../components/NewsLetter/NewsLetter'
import Slider from '../components/Slider/Slider'
import Sport from '../components/Sport/Sport'
import TopFooter from '../components/TopFooter/TopFooter'

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
    <Slider/>
    <NewArrivage/>
    <Sport/>
    <NewsLetter/>
    <TopFooter/>
    </>
  )
}
